[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p data/reports logs config"]

[start]
cmd = "python app.py"
