recipients:
  alerts: []
  daily_report: []
  errors: []

smtp:
  server: smtp.gmail.com
  port: 587
  use_tls: true
  sender_name: "Insurance News Agent"

templates:
  alert:
    subject: "Alerta - Insurance News Agent - {alert_type}"
    template_file: "alert_template.html"
  daily_report:
    subject: "Relatório Diário - Notícias de Seguros - {date}"
    template_file: "daily_report_template.html"
  error:
    subject: "Erro - Insurance News Agent - {error_type}"
    template_file: "error_template.html"
