name: "Debug Generate and Send report (manual)"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo
      GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      EMAIL_RECIPIENTS_DAILY: ${{ secrets.EMAIL_RECIPIENTS_DAILY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report
        run: python -u src/main.py --action collect

      - name: Resolve latest report path
        id: rp
        shell: bash
        run: |
          RP="$(ls -t data/reports/* 2>/dev/null | head -1 || true)"
          echo "path=$RP" >> "$GITHUB_OUTPUT"
          if [ -z "$RP" ]; then
            echo "::warning::No files found in data/reports"
          fi

      - name: Send email (optional)
        if: ${{ steps.rp.outputs.path != '' && env.GMAIL_EMAIL != '' && env.GMAIL_APP_PASSWORD != '' && env.EMAIL_RECIPIENTS_DAILY != '' }}
        run: python -u scripts/send_daily_email.py --report "${{ steps.rp.outputs.path }}"

      - name: Upload latest report
        if: ${{ steps.rp.outputs.path != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: latest-report
          path: ${{ steps.rp.outputs.path }}
          if-no-files-found: error
          retention-days: 7

      - name: Upload reports folder (optional)
        uses: actions/upload-artifact@v4
        with:
          name: reports-folder
          path: data/reports
          if-no-files-found: warn
          retention-days: 7
